name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.svcaccount }}
          project_id: tensile-tenure-423308-e5

      - name: Run install
        run: npm i

      - name: Run unit tests
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ccd07177-9cac-47df-b962-99626da546e1
          slug: imxale/derniersTest

      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account --key-file=./tensile-tenure-423308-e5-0fa52aa16d6a.json

      - name: Deploy Google function
        run: |
          gcloud functions deploy dernierstestaxel --gen2 --runtime=nodejs20 --region=us-east1 --source=. --entry-point=dernierstestaxel --trigger-http
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.project_id }}

      - name: Install Java
        run: sudo apt-get install -y openjdk-8-jdk

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar xf apache-jmeter-5.6.3.tgz

      - name: Copy custom JMeter properties
        run: |
          cp tests/stress/jmeter.properties apache-jmeter-5.6.3/bin/

      - name: create Bearer token
        run: export BEARER=$(gcloud auth print-identity-token)

      - name: Run JMeter tests
        run: |
          apache-jmeter-5.6.3/bin/jmeter -n -t tests/stress/test_plan.jmx -l test_results.csv -JIDENTITY_TOKEN=${{ env.BEARER }}

      - name: Install latency-lingo-cli
        run: |
          curl -L https://github.com/latency-lingo/cli/releases/latest/download/latency-lingo-cli_linux_amd64.tar.gz \
           | tar -xz

      - name: Upload JMeter report to Lingo
        run: ./latency-lingo-cli publish --file ./test_results.csv --label "derniers test" --api-key 814f97a2-f518-4384-94dc-dea39bc494fc
