name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.svcaccount }}
          project_id: tensile-tenure-423308-e5

      - name: Run install
        run: npm i

      - name: Run unit tests
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ccd07177-9cac-47df-b962-99626da546e1
          slug: imxale/derniersTest

      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account --key-file=./awesome-height-403820-c06ee3b3a086.json

      - name: Deploy Google function
        run: |
          gcloud functions deploy derniers-test --gen2 --runtime=nodejs20 --region=us-east1 --source=. --entry-point=helloGET --trigger-http
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.project_id }}
